# Generated by Django 4.1.7 on 2023-03-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
